### ISSUE TITLE
Recent updates?

### ISSUE THREAD

**Issue by spencercadams** [softlayer/softlayer-go#92] opened 2018-03-27 02:01 UTC
We're seeing our Go binaries that depend on softlayer-go erroring out on hosts that have user data defined with a marshaling error.  This previously worked, but now it does not.

We have a host with some userdata. We don't believe this userdata is new. However, suddenly our tools all started to break with a marshalling error when trying to read this host. This applies to old and new builds of the same tool, so it doesn't appear to be a code change on our side. Additionally, the `sl-cli` command that we would expect to clear said userdata doesn't appear to work as expected.

Is this to be expected or are we missing something?

**Comment by renier** [comment] 2018-03-27 02:28
@spencercadams Can you elaborate about the error and what you are doing?

Why do you think that an error unmarshaling user data (json?) is related to softlayer-go? What is the error specifically? Steps to reproduce?

**Comment by aughr** [comment] 2018-03-27 17:27
This call:

```
https://api.softlayer.com/rest/v3/SoftLayer_Account/getHardware.json?objectMask=mask%5Bid%3Bhostname%3Bdomain%3BfullyQualifiedDomainName%3BprimaryIpAddress%3BprimaryBackendIpAddress%3BfrontendNetworkComponents%5Bid%2Cname%2Cport%2CmacAddress%2Cstatus%2CprimarySubnet%5Bcidr%2Cgateway%2CnetworkVlanId%5D%5D%3BbackendNetworkComponents%5Bid%2Cname%2Cport%2CmacAddress%2Cstatus%2CprimarySubnet%5Bcidr%2Cgateway%2CnetworkVlanId%5D%5D%3BprimaryNetworkComponent%5Bid%2Cname%2Cport%2CmacAddress%2Cstatus%2CprimarySubnet%5Bcidr%2Cgateway%2CnetworkVlanId%5D%5D%3BprimaryBackendNetworkComponent%5Bid%2Cname%2Cport%2CmacAddress%2Cstatus%2CprimarySubnet%5Bcidr%2Cgateway%2CnetworkVlanId%5D%5D%3BtagReferences%5Bid%2Ctag%5Bid%2Cname%5D%5D%3BuserData%3BhardDriveCount%3Brack%3BserialNumber%3BbillingItem%5Bid%2CorderItem%5Bid%2Corder%5Bid%2Cquote%5D%5D%5D%3BbackendRouters%5Bid%2Chostname%5D%3BhardwareStatus%5Bid%2Cstatus%5D%5D
```

constructed by `softlayer-go`, returns fragments like:

```
    "userData": {
      "hardwareAttributeTypeId": 47,
      "id": 1234,
      "value": "my user data",
      "hardwareAttributeType": {
        "keyname": "USER_DATA",
        "name": "User Data"
      }
    }
```
Which does not match the expected type of `SoftLayer_Hardware_Attribute[]` here: https://softlayer.github.io/reference/datatypes/SoftLayer_Hardware/

**Comment by renier** [comment] 2018-03-27 18:48
@aughr Does the same happen if you go directly to the api endpoint using curl?
```
https://api.softlayer.com/rest/v3/SoftLayer_Account/getHardware.json?objectMask=mask[id;hostname;domain;fullyQualifiedDomainName;primaryIpAddress;primaryBackendIpAddress;frontendNetworkComponents[id,name,port,macAddress,status,primarySubnet[cidr,gateway,networkVlanId]];backendNetworkComponents[id,name,port,macAddress,status,primarySubnet[cidr,gateway,networkVlanId]];primaryNetworkComponent[id,name,port,macAddress,status,primarySubnet[cidr,gateway,networkVlanId]];primaryBackendNetworkComponent[id,name,port,macAddress,status,primarySubnet[cidr,gateway,networkVlanId]];tagReferences[id,tag[id,name]];userData;hardDriveCount;rack;serialNumber;billingItem[id,orderItem[id,order[id,quote]]];backendRouters[id,hostname];hardwareStatus[id,status]]
```

**Comment by spkane** [comment] 2018-03-27 22:51
Using `slcli`:

```
$ slcli --format json call-api Hardware_Server getObject --id 123456 --mask 'id,userData'
{
    "id": 123456,
    "userData": {
        "hardwareAttributeTypeId": 47,
        "id": 11857,
        "value": "bp user data",
        "hardwareAttributeType": {
            "keyname": "USER_DATA",
            "name": "User Data"
        }
    }
}
```

but expecting:
```
{
    "id": 123456,
    "userData": [{
        "hardwareAttributeTypeId": 47,
        "id": 11857,
        "value": "bp user data",
        "hardwareAttributeType": {
            "keyname": "USER_DATA",
            "name": "User Data"
        }
    }]
}
```

**Comment by renier** [comment] 2018-03-28 01:02
@spkane Yes, so what I'm seeig is that this is a softlayer-api issue, rather than softlayer-go. The api team monitors the _softlayer_ tag in stackoverflow for questions. You should send this over there.

**Comment by follower46** [comment] 2018-04-03 15:20
I believe this issue is fixed now.

**Closed** 2018-04-03 15:29 UTC

**Comment by spkane** [comment] 2018-04-03 19:53
Seems to be working. Thank you all!
