### ISSUE TITLE
Masks to get Network_Vlan data don't returns local properties

### ISSUE THREAD

**Issue by acamacho82** [softlayer/softlayer-go#44] opened 2017-03-23 17:38 UTC
Following code returns different values depending of EndPoint.
```go
mask := "networkSpace"
vlans, err := service.Mask(mask).GetNetworkVlans()
```
When using default endPoint `(https://api.softlayer.com/rest/v3)`, the result is:
```
{"networkSpace":"PRIVATE"}
```
And for `https://api.softlayer.com/xmlrpc/v3/`  is:
```
{"accountId":307608,"id":1360413,"modifyDate":"2016-12-05T13:49:35-06:00","name":"testrcv1","networkSpace":"PRIVATE","primarySubnetId":1282429,"vlanNumber":819}
```
This happens when the endpoint is REST and when only relational properties are set in the mask. I verified this for  SoftLayer_Account::getNetworkVlans and SoftLayer_Network_Vlan::getObject.

With any other REST client, like Insomnia or ARC, the result is like above (XMLRPC).

On this case, the result should display all local properties and the relational property set in the mask.

**Comment by renier** [comment] 2017-03-26 22:49
@acamacho82 I used Paw, and it returns something like `[{"networkSpace": "PUBLIC"}]` without the other properties. It is not true that the result should display all local properties when you are specifying a mask. The problem is that the REST API endpoint is not very consistent in this. It will sometimes show additional local properties that are not included in the object mask, other times you have to specify the local properties in the mask to get them to show up.

In any case, when using an object mask, you should always specify all the properties you want to see.

Closing, as this is a consistency issue in the API and not a bug in the client code.

**Closed by renier** 2017-03-26 22:49 UTC

**Comment by acamacho82** [comment] 2017-03-27 00:26
>  _It is not true that the result should display all local properties when you are specifying a mask for a relational property_

Please, review documentation https://sldn.softlayer.com/article/object-Masks#Property 

> The object mask ` mask.networkComponents` when calling SoftLayer_Hardware::getObject **will return the SoftLayer_Hardware object**, in addition to an array "networkComponents" containing the SoftLayer_Network_Components associated with that hardware.

According to documentation, the mask should return all local properties unless than an specific local property was set in the mask.

**Comment by renier** [comment] 2017-03-27 00:57
@acamacho82 I recommend you go to stackoverflow (tag your question with 'softlayer') so that you can get clarification on the intended behavior from the api folks.
